### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [21]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [23]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### sentences
sent=[  "The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"]

In [25]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [26]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [27]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8060, 7509, 6216, 795, 5199, 4928], [4694, 3039, 6216, 2307, 8978, 4531], [7865, 3935, 7499, 1959], [8060, 9606, 6216, 9757, 8060, 6547], [4941, 264, 2558, 6216, 2307, 8978, 4531], [1880, 6216, 2307, 8978, 243, 5728]]


### Word Embedding Represntation

In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [30]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8060 7509 6216  795 5199 4928]
 [   0    0    0    0 4694 3039 6216 2307 8978 4531]
 [   0    0    0    0    0    0 7865 3935 7499 1959]
 [   0    0    0    0 8060 9606 6216 9757 8060 6547]
 [   0    0    0 4941  264 2558 6216 2307 8978 4531]
 [   0    0    0    0 1880 6216 2307 8978  243 5728]]


In [31]:
## 10 feature dimesnions
dim=10


In [32]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [34]:

embedded_docs[0]

array([   0,    0,    0,    0, 8060, 7509, 6216,  795, 5199, 4928],
      dtype=int32)

In [35]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 38ms/step


array([[ 0.00724568, -0.03449657, -0.03182955,  0.00810558,  0.04997626,
        -0.02550136,  0.04471089,  0.03317589, -0.04391397, -0.00041975],
       [ 0.00724568, -0.03449657, -0.03182955,  0.00810558,  0.04997626,
        -0.02550136,  0.04471089,  0.03317589, -0.04391397, -0.00041975],
       [ 0.00724568, -0.03449657, -0.03182955,  0.00810558,  0.04997626,
        -0.02550136,  0.04471089,  0.03317589, -0.04391397, -0.00041975],
       [ 0.00724568, -0.03449657, -0.03182955,  0.00810558,  0.04997626,
        -0.02550136,  0.04471089,  0.03317589, -0.04391397, -0.00041975],
       [ 0.04076688, -0.0254578 ,  0.01853308, -0.03239413, -0.0339545 ,
         0.04540728, -0.03853453,  0.02764677,  0.01774391,  0.00254985],
       [ 0.00443375,  0.03929533, -0.01657411,  0.03180127, -0.04481   ,
        -0.02663199,  0.04940125, -0.02399793, -0.02894895,  0.03218622],
       [ 0.0180077 ,  0.04197855, -0.02994322, -0.02055211,  0.04839735,
         0.01377538, -0.04182384, -0.02771622

In [36]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 31ms/step
[[[ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626
   -0.02550136  0.04471089  0.03317589 -0.04391397 -0.00041975]
  [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626
   -0.02550136  0.04471089  0.03317589 -0.04391397 -0.00041975]
  [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626
   -0.02550136  0.04471089  0.03317589 -0.04391397 -0.00041975]
  [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626
   -0.02550136  0.04471089  0.03317589 -0.04391397 -0.00041975]
  [ 0.04076688 -0.0254578   0.01853308 -0.03239413 -0.0339545
    0.04540728 -0.03853453  0.02764677  0.01774391  0.00254985]
  [ 0.00443375  0.03929533 -0.01657411  0.03180127 -0.04481
   -0.02663199  0.04940125 -0.02399793 -0.02894895  0.03218622]
  [ 0.0180077   0.04197855 -0.02994322 -0.02055211  0.04839735
    0.01377538 -0.04182384 -0.02771622 -0.00568897  0.03470116]
  [-0.00056251 -0.00268074 -0.00844208 -0.03373687  0.00241417


In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 8060, 7509, 6216,  795, 5199, 4928],
      dtype=int32)

In [38]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 16ms/step
[[ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626 -0.02550136
   0.04471089  0.03317589 -0.04391397 -0.00041975]
 [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626 -0.02550136
   0.04471089  0.03317589 -0.04391397 -0.00041975]
 [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626 -0.02550136
   0.04471089  0.03317589 -0.04391397 -0.00041975]
 [ 0.00724568 -0.03449657 -0.03182955  0.00810558  0.04997626 -0.02550136
   0.04471089  0.03317589 -0.04391397 -0.00041975]
 [ 0.04076688 -0.0254578   0.01853308 -0.03239413 -0.0339545   0.04540728
  -0.03853453  0.02764677  0.01774391  0.00254985]
 [ 0.00443375  0.03929533 -0.01657411  0.03180127 -0.04481    -0.02663199
   0.04940125 -0.02399793 -0.02894895  0.03218622]
 [ 0.0180077   0.04197855 -0.02994322 -0.02055211  0.04839735  0.01377538
  -0.04182384 -0.02771622 -0.00568897  0.03470116]
 [-0.00056251 -0.00268074 -0.00844208 -0.03373687  0.00241417  0.02483254